### ISSUE TITLE
stateChanged is never called.

### ISSUE THREAD

**Issue by Arideno** [maxxfrazer/ARKit-FocusNode#3]
Hello. I discovered that stateChanged is never called. Can you resolve this issue?

**Comment by maxxfrazer** [comment]
Hi, it is called in `FocusNode.swift`
https://github.com/maxxfrazer/ARKit-FocusNode/blob/master/FocusNode/FocusNode.swift#L318

Let me know if that's ok and I'll close the issue if it is 👍

**Comment by maxxfrazer** [comment]
Hi @Arideno, it is called in `FocusNode.swift`
https://github.com/maxxfrazer/ARKit-FocusNode/blob/master/FocusNode/FocusNode.swift#L318

Let me know if that's ok and I'll close the issue if it is 👍

**Comment by Arideno** [comment]
I know, but, for instance, FocusSquare does not change its animation when a plane is detected, it’s just the same.

**Comment by maxxfrazer** [comment]
Aha, I'm assuming you mean in the `Example/`, and you haven't created it yourself?
The plane detection is switched off in the example, I have added it in now; thanks for letting me know there was an issue somewhere with that.
The function was called, but `self.onPlane` was always false; the pod itself is unchanged. and your version should be fine.
