### ISSUE TITLE
Queueless

### ISSUE THREAD

**Issue by digitallysavvy** [maxxfrazer/ARKit-FocusNode#9]
Within `queueless` the view delegate has changed from `ARSCNVIEW` to `ARSmartHitTest` but when trying to pass the scene view cast to `ARSmartHitTest` this line fails 

```
guard let view = self.viewDelegate as? (ARSCNView & ARSmartHitTest) else {
	print("FocusNode viewDelegate must be an ARSCNView for now")
	return
}
```

**Comment by maxxfrazer** [comment]
@digitallysavvy you should just need to add the following code somewhere in your app:
`extension ARSCNView: ARSmartHitTest {}`
